### ISSUE TITLE
不同组织/项目下的环境不能重名

### ISSUE THREAD

**Issue by mt5225** [idcos/cloudiac#188]
- 环境名只需要在项目范围内保持唯一， 但目前跨组织和跨项目的环境均不能重名

**Comment by licairong** [comment]
环境名称是项目下唯一，跨组织和跨项目的环境是可以重名的，但同一项目下已归档的环境名称也在被检查的范围内，你可能是碰到了与归档环境同名的情况，这个后续我们考虑是否对环境增加删除功能，或者已归档的环境排队在检查范围之外
