### ISSUE TITLE
clone 代码步骤出错后任务无法统计环境资源

### ISSUE THREAD

**Issue by jxinging** [idcos/cloudiac#210]
当 clone 代码出错时会因为没有 code 目录导致 collect 步骤出错。

是否可以先创建 code 目录，并创建好 cloudiac.tf ，这样即使 clone 失败也可以正常 collect？

**Comment by jxinging** [comment]
另，现在 code 目录及 _cloudiac.tf 文件的创建是在 checkout 和 init 步骤进行的，如果在这些步骤之前用户调用自定义命令可能会因为 code 目录不存在而出错。
考虑将这类初始化动作放到容器启动命令中执行？

**Comment by licairong** [comment]
这些前置操作可以放到整个任务的最前面执行，不影响后面流程的调用
