### ISSUE TITLE
docker-compose方式 iac-portal 起不来

### ISSUE THREAD

**Issue by jaty613** [idcos/cloudiac#236]
iac-portal    | time="2022-01-11T12:30:41.711" level=info msg="/Users/xing/workspace/go/cloudiac/cloudiac/portal/libs/db/mysql_gorm.go:453\n[error] failed to initialize database, got error dial tcp 172.20.0.3:3306: connect: no route to host"
iac-portal    | time="2022-01-11T12:30:41.711" level=fatal msg="dial tcp 172.20.0.3:3306: connect: no route to host"

**Comment by jxinging** [comment]
第一次启动时可能因为 mysql 服务在初始化数据导致 iac-portal 连接 mysql 出错，可以尝试 docker-compose up -d 重启所有服务再查看是否正常。

如果依然无法解决可以提供一下 docker-compose.yml 和 脱敏后的 .env 配置。

**Comment by jaty613** [comment]
# auto-replace-from: configs/dotenv.sample
# 平台管理员账号密码(均为必填)
# 该账号密码只在系统初始化时使用，后续修改不影响己创建的账号
IAC_ADMIN_EMAIL="admin@example.com"
# 密码要求长度大于 8 且包含字母、数字、特殊字符
IAC_ADMIN_PASSWORD="a@12344321"

# 加密密钥配置(必填)
# 敏感数据使用该密钥进行加密
SECRET_KEY="acaca22dadfa"

# IaC 对外提供服务的地址(必填), 示例: http://cloudiac.example.com
# 该地址需要带协议(http/https)，结尾不可以加 "/"
PORTAL_ADDRESS="http://192.168.122.1"

# consul 地址(必填)，示例: private.host.ip:8500
# 需要配置为机器的内网 ip:port，不可使用 127.0.0.1
CONSUL_ADDRESS="192.168.122.1:8500"

# mysql 配置(必填)
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_DATABASE=cloudiac
MYSQL_USER=cloudiac
MYSQL_PASSWORD="mysqlpass"

# portal 服务注册信息配置 (均为必填)
## portal 服务的 IP 地址， 容器化部署时无需修改, 手动部署时配置为内网 IP
SERVICE_IP=iac-portal
## portal 服务注册的 id(需要保证唯一)
SERVICE_ID=iac-portal-01
## portal 服务注册的 tags
SERVICE_TAGS="iac-portal;portal-01"

# logger 配置
LOG_DEVEL="debug"

# SMTP 配置(该配置只影响邮件通知的发送，不配置不影响其他功能)
SMTP_ADDRESS=smtp.example.com:25
SMTP_USERNAME=user@example.com
SMTP_PASSWORD=""
SMTP_FROM_NAME=IaC
SMTP_FROM=support@example.com

# KAFKA配置(kafka 任务结果回调使用，不配置不影响其他功能)
KAFKA_TOPIC="IAC_TASK_REPLY"
KAFKA_GROUP_ID=""
KAFKA_PARTITION=0
## example: KAFKA_BROKERS: ["kafka.example.com:9092", "..."]
KAFKA_BROKERS=[]
KAFKA_SASL_USERNAME=""
KAFKA_SASL_PASSWORD=""


######### 以下为 runner 配置 #############
# runner 服务注册配置(均为必填)
## runner 服务的 IP 地址， 容器化部署时无需修改, 手动部署时配置为内网 IP
RUNNER_SERVICE_IP=ct-runner
## runner 服务注册的 id(需要保证唯一)
RUNNER_SERVICE_ID=ct-runner-01
RUNNER_SERVICE_TAGS="ct-runner;runner-01"

## 是否开启 offline mode，默认为 false
RUNNER_OFFLINE_MODE="false"

**Comment by jxinging** [comment]
麻烦再提供一下 docker-compose.yml 配置 @jaty613

**Comment by jaty613** [comment]
# auto-replace-from: docker/docker-compose.yml
version: "3.2"
services:
  iac-portal:
    container_name: iac-portal
    image: "cloudiac/iac-portal:v0.8.1"
    volumes:
      - type: bind
        source: /usr/yunji/cloudiac/var
        target: /usr/yunji/cloudiac/var
      - type: bind
        source: /usr/yunji/cloudiac/.env
        target: /usr/yunji/cloudiac/.env
    ports:
      - "9030:9030"
    depends_on:
      - mysql
      - consul
    restart: always

  ct-runner:
    container_name: ct-runner
    image: "cloudiac/ct-runner:v0.8.1"
    volumes:
      - type: bind
        source: /usr/yunji/cloudiac/var
        target: /usr/yunji/cloudiac/var
      - type: bind
        source: /usr/yunji/cloudiac/.env
        target: /usr/yunji/cloudiac/.env
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "19030:19030"
    depends_on:
      - consul
    restart: always

  ct-worker:
    image: "cloudiac/ct-worker:v0.8.1"
    container_name: "ct-worker-say-hi"
    # 添加该服务只是为了自动 pull 镜像，并不需要后台运行
    command: ["echo", "hello world!"]
    restart: "no"

  iac-web:
    container_name: iac-web
    image: "cloudiac/iac-web:v0.8.0"
    ports:
      - 80:80
    restart: always
    depends_on:
      - iac-portal

  mysql:
    container_name: mysql
    image: "mysql:8.0"
    command: [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    volumes:
      - type: bind
        source: /usr/yunji/cloudiac/var/mysql
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    restart: always

  consul:
    container_name: consul
    image: "consul:latest"
    volumes:
      - type: bind
        source: /usr/yunji/cloudiac/var/consul
        target: /consul/data
    ports:
      - "8500:8500"
    command: >
      consul agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0
      -client=0.0.0.0 -enable-script-checks=true -data-dir=/consul/data
    restart: always

**Comment by jxinging** [comment]
请执行以下命令，确认一下服务状态

```bash
cd /usr/yunji/cloudiac
docker-compose ps
docker-compose logs --tail=10 mysql iac-portal
docker-compose exec iac-portal ping -c3 mysql
docker-compose exec iac-portal nc -vz mysql 3306
```

**Comment by jaty613** [comment]
[root@localhost cloudiac]# docker-compose ps
      Name                    Command                 State                                                Ports                                          
----------------------------------------------------------------------------------------------------------------------------------------------------------
consul             docker-entrypoint.sh consu ...   Up           8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8500->8500/tcp, 8600/tcp,      
                                                                 8600/udp                                                                                 
ct-runner          /bin/sh -c ./ct-runner           Restarting                                                                                            
ct-worker-say-hi   echo hello world!                Exit 0                                                                                                
iac-portal         /bin/sh -c ./iac-portal          Restarting                                                                                            
iac-web            nginx -g daemon off;             Up           443/tcp, 0.0.0.0:80->80/tcp                                                              
mysql              docker-entrypoint.sh --cha ...   Up           0.0.0.0:3306->3306/tcp, 33060/tcp

**Comment by jxinging** [comment]
我这边测试 mysql 启动后的最后几行日志如下：
```
2022-01-12T10:38:23.502820Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2022-01-12T10:38:23.503047Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2022-01-12T10:38:23.506210Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-01-12T10:38:23.544331Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2022-01-12T10:38:23.544431Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```

看你的日志缺少了最后一行 “ready for connections. Version: '8.0.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306”，
可能是端口监听失败，可以使用命令 `docker-compose logs --f mysql` 观察下是否有报错
