### ISSUE TITLE
合规：检测环境时提示未知错误

### ISSUE THREAD

**Issue by mt5225** [idcos/CloudIaC#29]
<img width="1065" alt="Screen Shot 2021-10-14 at 4 21 07 PM" src="https://user-images.githubusercontent.com/1159271/137408340-7fd611bf-cbcb-49d5-bf26-64adeb6934c2.png">

**Comment by chenzhanjia-idcos** [comment]
该云模板对应的仓库无法访问，已经恢复该模板的仓库。

**Comment by mt5225** [comment]
thanks, 错误信息可以更明确一些
