### ISSUE TITLE
portal/services: 获取新 repoAddr(带 token) github url拼接错误

### ISSUE THREAD

**Issue by guanyux** [idcos/cloudiac#374]
![image](https://user-images.githubusercontent.com/100672734/157365866-b25d8b45-a5f8-4661-bea6-902e7f71b2c7.png)

**Comment by guanyux** [comment]
提交了一个pr 解决该问题，请review ：https://github.com/idcos/cloudiac/pull/376

**Comment by xiaohei417** [comment]
该问题的原因是cloudiac访问github私有仓库拉取代码时指定的用户名为空导致的异常，目前cloudiac支持4种vcs, 每一种vcs的鉴权方式都有些许差异。

解决方案：
- 生成代码仓库地址时，指定用户名
    - 示例： https://{username}:{token}@github.com/xioahei417/tf-module.git

修复版本：v0.10.0
PR: #378 

感谢您对CloudIaC的支持！
