### ISSUE TITLE
环境被销毁后是否要清空自动销毁设置？

### ISSUE THREAD

**Issue by jxinging** [idcos/cloudiac#418]
### 背景
考虑这样一个场景：给环境设置一个自动销毁时间(如 20220324 22:16:00)，当环境被销毁后其自动销毁时间并不会清空，下一次重新部署该环境后可能因为已过自动销毁时间，环境在创建成功后立即触发了自动销毁

### 讨论
- 环境被销毁后是否应该清空自动销毁设置？
- 可能有环境创建后几个小时自动销毁的需求（环境部署成功后几个小时自动销毁），如果销毁后清空配置，再创建环境又需要重新配置自动销毁，用户体验不好

**Comment by brianchenl** [comment]
我们比较常用的场景，是每个工作日晚9点定时销毁环境，现在是每天都要设置，我希望有能有个周期性的销毁定时。也可以设置一次性的定时，两者的区别在于是否在销毁后被清理。

**Comment by xiaodaiit** [comment]
增加一个可选择项,选中以后,可以下次接着规则继续执行,手动取消以后,下次不执行.同时给与提示.  因为场景有些涉及到开发环境,测试环境,已经线上部署环境对于是否定时销毁的需求是不一样的

**Comment by licairong** [comment]
- 对于设置了绝对时间的，销毁后该时间应该清空
- 对于相对时间的设置，可以保留该设置
- @brianchenl 提到的定时场景，后续可以考虑增加周期性的销毁和关停功能

**Comment by chenzhanjia-idcos** [comment]
周期性的销毁和关停功能已实现。
