### ISSUE TITLE
[BUG] 销毁失败的环境无法归档

### ISSUE THREAD

**Issue by mt5225** [idcos/cloudiac#689]
### 联系方式

jerry@idcos.com

### CloudIaC 版本

1.0.1

### 问题描述

由于网络原因仓库无法检出，导致环境创建和销毁均无法成功，而“归档”按钮在环境处于销毁状态时才可点
导致该环境无法被归档

### 重现步骤

如上

### 期待的正确结果

在判断状态文件为空或未创建时，可进行归档操作

**Comment by chenzhanjia-idcos** [comment]
已经提供失败环境归档。
