### ISSUE TITLE
云模板可以设置必填变量

### ISSUE THREAD

**Issue by jxinging** [idcos/cloudiac#69]
为云模板添加变量时可以设置其为必填，这种变量在云模板里可以有默认值或者为空值，在使用该云模板创建环境时必需为这些变量赋值，否则不允许创建环境。 

使用场景：
1. 将云模板依赖的云商账号变量设置为必填，保证创建的环境里设置了云商账号
2. 第三方集成 IaC 时，只需要把必填变量导出供用户使用，其他变量在第三方平台用户不可见

**Comment by mt5225** [comment]
第二点需要再想想： 
- tf中的参数可以有default值，但可以在环境变量或tfvars中指定/覆盖，如  number of servers, 
- 第三方集以云模版定义的参数为准，还是可以直接穿透云模版限制直接指定 TF_VARS ?
- 是否允许第三方指定资源账号
