### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by mt5225** [idcos/cloudiac#718]
### CloudIaC 版本

1.0

### 请描述您的需求或者改进建议

通过 tf-summarize   总结plan 的结果

https://github.com/dineshba/tf-summarize

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1159271/197929697-0de6f60a-4488-4977-bd1f-182a4a4d5c7f.png">

**Comment by chenzhanjia-idcos** [comment]
Fixed in #775
