### ISSUE TITLE
VCS优化

### ISSUE THREAD

**Issue by licairong** [idcos/CloudIaC#82]
- [x] 各类型VCS在获取仓库列表时只获取该VCS帐号自身的仓库，不包括非该帐号下的public仓库
- [x] 目前VCS管理中没有提供编辑VCS功能，当VCS的token失效或重新生成后只能删除再添加，导致的问题是基于此VCS创建的云模板也需要做相应修改，为些增加VCS编辑功能，编辑时token编辑框处理方式与敏感型变量相同

**Comment by xiaohei417** [comment]
vcs的token传输、存储都要改成密文。
日志输出时也替换成 *****

**Comment by xiaohei417** [comment]
#99
