### ISSUE TITLE
环境A可以引用环境B的output

### ISSUE THREAD

**Issue by mt5225** [idcos/cloudiac#9]
- 组织内，环境的output可以作为其他环境的input

**Comment by jinxing-idcos** [comment]
是不是可以考虑把环境也当作资源，提供 cloudiac provider 来实现环境之间的引用

**Comment by jxinging** [comment]
计划通过 cloudiac provider 实现，目前己完成 provider 开发，但整体使用流程未打通，需要进一步跟进 @xiaohei417

**Comment by licairong** [comment]
cloudiac provider 已实现该功能
